print('Hellow World')
print('Hellow World')
print('Hellow World')
print('Hellow World')
print('Hellow World')
print('Hellow World')
print('Hellow cnx')
print('Hellow Thew')
print('แก้ไข Assignment4')
print('แก้ไข Assignment4 recap')